name = "Static Site"
address = "https://garfeng.github.io/static_site/"
root_path = "/static_site/"
database = "https://garfeng.github.io/static_site/config/test_data/"

default_model = "thread"

#markdown or bbcode
src_type = "markdown"

[model.thread]
name = "thread"
type = "thread"
title = "帖子"
src_type = "bbcode"
[model.thread.classes.game]
title = "游戏"

[model.thread.classes.document]
title = "文档"


[model.article]
name = "article"
type = "article"
title = "文章"
src_type = "bbcode"


[model.user]
name = "user"
type = "list"
title = "空间"

