name = "Static Site"
address = "https://xxx.xxx"
root_path = "/"
database = "http://localhost:8080/test_data"

default_model = "thread"

#markdown or bbcode
src_type = "markdown"

[model.thread]
name = "thread"
type = "thread"
title = "帖子"
src_type = "bbcode"
[model.thread.classes.game]
title = "游戏"

[model.thread.classes.document]
title = "文档"


[model.article]
name = "article"
type = "article"
title = "文章"
src_type = "bbcode"


[model.user]
name = "user"
type = "list"
title = "空间"

